## Hyper- and model parameters ###
MAX_EPOCHS = 100
BATCH_SIZE = 64
LEARNING_RATE = 0.00001
KEEP_PROB_TRAIN = 0.75
KEEP_PROB_VAL = 1.0
DECAYING_LEARNING_RATE = True

### Dataset and feature extraction parameters ###
DATASET_SIZE_TRAIN = 10
DATASET_SIZE_VAL = 1
NUM_UNITS = 256
NFFT = 256
NUMBER_BINS = int(NFFT/2+1)
STFT_OVERLAP = 0.75
#NUM_CLASSES = int(NUMBER_BINS/2)
NUM_CLASSES = NUMBER_BINS
AUDIO_dB_SPL = 60
BIN_WIZE = False

### Early stopping criteria ###
VALID_EVERY = 2000
MOVING_AVERAGE_ORDER = 5
STOP_COUNT = 20
