## Hyper- and model parameters ###
MAX_EPOCHS = 50
BATCH_SIZE = 16
LEARNING_RATE = 0.0001
KEEP_PROB_TRAIN = 0.75
KEEP_PROB_VAL = 1.0
DECAYING_LEARNING_RATE = True

### Dataset and feature extraction parameters ###
DATASET_SIZE_TRAIN = 5
DATASET_SIZE_VAL = 2
NUM_UNITS = 1024
NFFT = 256
NUMBER_BINS = int(NFFT/2+1)
STFT_OVERLAP = 0.75
NUM_CLASSES = NUMBER_BINS
AUDIO_dB_SPL = 60
BIN_WIZE = False

### Early stopping criteria ###
STOP_COUNT = 15
